(defun lambda (: x VarDef) (: body VarDef)
              :sort VarDef)
(defscope :function lambda :bind ((body 0) (x 0)))
(defun evil (: x VarDef) (: body VarDef) :sort VarDef)
(defmacro (evil 1 2)
          (lambda 1 2))
(defmacro (evil 2 1)
          (lambda 1 2))
(infer)
(exit)
